{
  'version': '3.8',
  'services':
    {
      'elasticsearch':
        {
          'image': 'elasticsearch:7.17.0',
          'environment': { 'discovery.type': 'single-node', 'ES_JAVA_OPTS': '-Xms512m -Xmx512m' },
          'ports': ['9200:9200'],
        },
      'kibana':
        {
          'image': 'kibana:7.17.0',
          'ports': ['5601:5601'],
          'environment': { 'ELASTICSEARCH_HOSTS': 'http://elasticsearch:9200' },
        },
      'logstash':
        {
          'image': 'logstash:7.17.0',
          'volumes':
            ['./monitoring/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf'],
          'ports': ['5044:5044'],
        },
    },
}
