-- migrations.sql
-- Auto-generated by Enterprise Organizer
-- Timestamp: 2025-10-05T20:14:44.537Z

-- Add your SQL statements here
CREATE TABLE IF NOT EXISTS example_table (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_example_table_name ON example_table(name);

-- Add comments
COMMENT ON TABLE example_table IS 'Example table auto-generated by Enterprise Organizer';
