import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Badge,
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui';
import AdminNavigationPanel from '@/components/admin/AdminNavigationPanel';
import { useAdminNavigation } from '@/hooks/useAdminNavigation';
import type { AdminNavigationTemplate } from '@/services/adminNavigation';
import { ArrowLeft, RefreshCcw, Rocket } from 'lucide-react';

const EmptyStateCard: React.FC<{ title: string; description: string }> = ({ title, description }) => (
  <Card className='border-dashed border-outline/40 bg-surface-container-low text-on-surface-variant'>
    <CardHeader>
      <CardTitle className='text-on-surface'>{title}</CardTitle>
    </CardHeader>
    <CardContent>
      <p className='md3-body-medium'>{description}</p>
    </CardContent>
  </Card>
);

export const AdminNavDemoPage: React.FC = () => {
  const navigate = useNavigate();
  const { categories, status, templateCount, refresh, error } = useAdminNavigation();
  const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null);
  const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null);

  useEffect(() => {
    if (status !== 'ready' || categories.length === 0) {
      return;
    }

    const hasSelection = selectedTemplateId && selectedCategoryId;
    if (!hasSelection) {
      const firstCategory = categories[0];
      const firstTemplate = firstCategory.templates[0] ?? null;
      setSelectedCategoryId(firstCategory.category_id);
      setSelectedTemplateId(firstTemplate?.template_id ?? null);
    }
  }, [categories, status, selectedCategoryId, selectedTemplateId]);

  const selectedTemplate = useMemo<AdminNavigationTemplate | null>(() => {
    if (!selectedTemplateId) {
      return null;
    }

    for (const category of categories) {
      const template = category.templates.find(item => item.template_id === selectedTemplateId);
      if (template) {
        return template;
      }
    }

    return null;
  }, [categories, selectedTemplateId]);

  const handleTemplateSelect = useCallback((categoryId: string, templateId: string) => {
    setSelectedCategoryId(categoryId);
    setSelectedTemplateId(templateId);
  }, []);

  const knowledgeAttributes = useMemo(() => {
    if (!selectedTemplate?.knowledge_graph_attributes) {
      return null;
    }
    return JSON.stringify(selectedTemplate.knowledge_graph_attributes, null, 2);
  }, [selectedTemplate]);

  return (
    <div className='space-y-6 p-6'>
      <header className='flex flex-wrap items-start justify-between gap-4 rounded-3xl border border-outline/20 bg-surface-container-high/70 p-5 backdrop-blur'>
        <div className='space-y-2'>
          <div className='inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-medium uppercase tracking-wide text-primary'>
            <Rocket className='h-3.5 w-3.5' /> Live admin navigation demo
          </div>
          <h1 className='text-2xl font-semibold text-on-surface md:text-3xl'>Workflow template navigation</h1>
          <p className='max-w-2xl text-sm text-on-surface-variant'>
            This surface demonstrates the real-time admin navigation metadata generated by the Template Watcher Service. Categories, subcategories, and workflow templates update instantly as files or database entries change.
          </p>
        </div>
        <div className='flex flex-wrap items-center gap-2'>
          <Button variant='text' leftIcon={<ArrowLeft className='h-4 w-4' />} onClick={() => navigate(-1)}>
            Back
          </Button>
          <Button variant='outlined' leftIcon={<RefreshCcw className='h-4 w-4' />} onClick={() => refresh()}>
            Force sync
          </Button>
          <Button variant='filled' onClick={() => navigate('/admin-dashboard')}>
            Open admin console
          </Button>
        </div>
      </header>

      <section className='grid gap-6 lg:grid-cols-[minmax(0,360px),minmax(0,1fr)]'>
        <div className='space-y-4'>
          <Card className='border-outline/20 bg-surface'>
            <CardHeader className='space-y-1'>
              <CardTitle className='md3-title-medium text-on-surface'>Navigation overview</CardTitle>
              <p className='md3-body-small text-on-surface-variant'>
                Connected to watcher service ·{' '}
                <Badge variant={status === 'ready' ? 'success' : status === 'error' ? 'error' : 'warning'}>
                  {status === 'ready' && 'Synced'}
                  {status === 'loading' && 'Syncing'}
                  {status === 'error' && 'Needs attention'}
                  {status === 'idle' && 'Idle'}
                </Badge>
              </p>
            </CardHeader>
            <CardContent className='space-y-4'>
              <div className='flex items-center justify-between rounded-2xl border border-outline/10 bg-surface-container-low px-3 py-2'>
                <span className='md3-body-small text-on-surface-variant'>Templates discovered</span>
                <span className='md3-title-medium text-on-surface'>{templateCount}</span>
              </div>
              {error ? (
                <EmptyStateCard
                  title='Unable to load navigation metadata'
                  description={error}
                />
              ) : null}
              <AdminNavigationPanel
                categories={categories}
                status={status}
                templateCount={templateCount}
                selectedCategoryId={selectedCategoryId}
                selectedTemplateId={selectedTemplateId}
                onSelectTemplate={handleTemplateSelect}
                onRefresh={refresh}
              />
            </CardContent>
          </Card>
        </div>

        <div className='space-y-4'>
          {status === 'loading' ? (
            <Card className='animate-pulse border-outline/15 bg-surface-container-low'>
              <CardHeader>
                <CardTitle className='text-on-surface-variant'>Loading template details…</CardTitle>
              </CardHeader>
              <CardContent className='space-y-3'>
                <div className='h-4 rounded-full bg-outline/20' />
                <div className='h-4 rounded-full bg-outline/15' />
                <div className='h-32 rounded-2xl bg-outline/10' />
              </CardContent>
            </Card>
          ) : null}

          {status === 'ready' && selectedTemplate ? (
            <>
              <Card className='border-outline/15 bg-surface'>
                <CardHeader className='space-y-2'>
                  <CardTitle className='text-on-surface'>{selectedTemplate.name}</CardTitle>
                  {selectedTemplate.description ? (
                    <p className='md3-body-small text-on-surface-variant'>{selectedTemplate.description}</p>
                  ) : null}
                </CardHeader>
                <CardContent className='space-y-3'>
                  <div className='flex flex-wrap gap-2'>
                    <Badge variant='primary'>Category: {selectedTemplate.category}</Badge>
                    {selectedTemplate.subcategory ? (
                      <Badge variant='secondary'>Subcategory: {selectedTemplate.subcategory}</Badge>
                    ) : null}
                    <Badge variant='outline'>Schema v{selectedTemplate.schema_version || '1.0.0'}</Badge>
                    {selectedTemplate.icon ? <Badge variant='tertiary'>{selectedTemplate.icon}</Badge> : null}
                  </div>

                  {selectedTemplate.status_steps?.length ? (
                    <div className='space-y-2'>
                      <p className='md3-label-medium text-on-surface'>Workflow steps</p>
                      <div className='grid gap-2 sm:grid-cols-2'>
                        {selectedTemplate.status_steps.map(step => (
                          <Card key={step.id} className='border-outline/20 bg-surface-container-low p-3'>
                            <p className='md3-body-medium text-on-surface'>
                              {step.index + 1}. {step.title}
                            </p>
                            {step.description ? (
                              <p className='md3-body-small text-on-surface-variant'>{step.description}</p>
                            ) : null}
                            {step.status ? (
                              <Badge variant='secondary' className='mt-2 w-fit'>
                                {step.status}
                              </Badge>
                            ) : null}
                          </Card>
                        ))}
                      </div>
                    </div>
                  ) : null}
                </CardContent>
              </Card>

              <Card className='border-outline/15 bg-surface'>
                <CardHeader>
                  <CardTitle className='md3-title-small text-on-surface'>Knowledge graph attributes</CardTitle>
                </CardHeader>
                <CardContent>
                  {knowledgeAttributes ? (
                    <pre className='max-h-[320px] overflow-auto rounded-2xl bg-surface-container-low p-3 text-xs text-on-surface'>
                      {knowledgeAttributes}
                    </pre>
                  ) : (
                    <p className='md3-body-small text-on-surface-variant'>No knowledge graph attributes recorded yet.</p>
                  )}
                </CardContent>
              </Card>

              {selectedTemplate.workflow_summary ? (
                <Card className='border-outline/15 bg-surface'>
                  <CardHeader>
                    <CardTitle className='md3-title-small text-on-surface'>Workflow summary</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <pre className='max-h-[240px] overflow-auto rounded-2xl bg-surface-container-low p-3 text-xs text-on-surface'>
                      {JSON.stringify(selectedTemplate.workflow_summary, null, 2)}
                    </pre>
                  </CardContent>
                </Card>
              ) : null}
            </>
          ) : null}

          {status === 'ready' && templateCount === 0 ? (
            <EmptyStateCard
              title='No templates discovered yet'
              description='Drop workflow templates into the watched directories or add them via the admin interface to populate this navigation surface.'
            />
          ) : null}

          {status === 'error' && !selectedTemplate ? (
            <EmptyStateCard
              title='Navigation unavailable'
              description='We were unable to fetch admin navigation metadata. Try refreshing or check the watcher service logs.'
            />
          ) : null}
        </div>
      </section>
    </div>
  );
};

export default AdminNavDemoPage;
